### ISSUE TITLE
Anna skill does not function as it would in-game

### ISSUE THREAD

**Issue by AristocratMC** [umang-p/brainlets#16]
Anna's skill currently applies static buffs based on position in the formation, but the behavior is dynamic in-game (e.g. front row really means frontmost row with at least 1 T-Doll in it, see below illustrations)

- [1 column](https://cdn.discordapp.com/attachments/564053529778716672/599245590324314142/-bqqbQ5-ci38XtZ7zT3cS112-ku.png)
- [2 columns](https://cdn.discordapp.com/attachments/564053529778716672/599245499077230622/-bqqbQ5-cevtXtZ84T3cS112-ku.png)
- [3 columns](https://cdn.discordapp.com/attachments/564053529778716672/599245549811531817/-bqqbQ5-k83eXtZ87T3cS112-ku.png)

**Comment by umang-p** [comment]
Didn't know it worked this way, thanks.

Fixed in [https://github.com/umang-p/brainlets/commit/d222b94fc2a6e47f40f1e8e5ee681c3068e24763](https://github.com/umang-p/brainlets/commit/d222b94fc2a6e47f40f1e8e5ee681c3068e24763)
