### ISSUE TITLE
K2 damage calculation does not appear to be correct when armor is involved

### ISSUE THREAD

**Issue by AristocratMC** [umang-p/brainlets#20]
(I'll probably get to this in a few days if you are busy, leaving issue here so I don't lose track.)

**Reproduction steps:**
* Add K2 to sim
* Set enemy evasion to 0, and armor to K2's starting FP * 52% + 15 (to counteract AP)

**Expected result:**
* K2 will deal 15 damage per shot, because armor will reduce her hits to 1x3 damage each dummy, since armor should be calculated for each of her three 52% damage hits. 

**Actual result:**
* K2 deals some incomprehensible amount of damage per shot
    * At 52 armor (K2 expected to deal 37x3 damage per shot), she deals 376 damage per shot
    * At 88+ armor (enough to counteract base FP of 73 + 15 AP), she deals 10 damage per shot. This should be 15, but for some reason it is 10. 

**Analysis:**
At the very least, we know the damage calculation for this unit in particular is only calculating armor once. However this doesn't explain the other anomaly of only dealing 10 damage per shot even though K2 does a triple shot and thus should deal 15. 

**To-Do:**
* Verify that armor actually applies 3 times to K2's damage in-game
* Debug and step through the JS calculation routine

**Comment by umang-p** [comment]
Commit [https://github.com/umang-p/brainlets/commit/40a1313276031c9bcf4bd5939c699d1fa93246de](https://github.com/umang-p/brainlets/commit/40a1313276031c9bcf4bd5939c699d1fa93246de) will fix her damage against high armor enemies, letting her deal 15 damage per shot. However, taking crit into account will add a multiplier of 1.34 with default equips, so she will be shown as doing 20 damage per shot. I am unaware of whether or not the game rounds up or down when a critical hit occurs at minimum damage so for now I will leave it as it is. 

Leaving this issue open as I believe there is a problem with her skill switching modes upon cooldown. (will investigate further tomorrow)

**Comment by umang-p** [comment]
Turns out there was an issue when switching from note to fever mode. Fixed in 9d9442c50d76299b83c86676f4cf95b97fac79ff

K2's skill should function properly now so I'm closing this. Please open another issue if you find any problems.
