### ISSUE TITLE
K11 damage calculation does not appear to work correctly for bosses

### ISSUE THREAD

**Issue by AristocratMC** [umang-p/brainlets#22]
**Reproduction steps:**
* Add K11 to sim 
* Toggle on boss checkbox
* Check the damage dealt by her skill

**Expected result:**
* K11 (76 FP with default configs) has the following skill: 
    ```Launch a grenade based on the number on dummy links, dealing 4x damage to enemies within a radius of 1 unit. Enemies are hit by a grenade are marked for 3 seconds. If K11's grenades hit a marked enemy, they take an additional 2x damage.```
* Against bosses, all 5 of her grenades will hit. She will deal 4x damage with the first nade, 6x damage with the other four. 
    * This results in a 28x effective multiplier, meaning her skill should deal 2128 damage. 

**Actual result:**
* K11 deals 3040 damage (40x FP)

**Analysis:**
This is the result of the following factors: 
    1. Stacking nades dealing double damage instead of 6x (4x+2x) damage. 
    2. Stacking nades applying the damage amplification to all five nades, instead of only the four nades after the initial hit

Pull request #21 fixes this issue for now, but wondering if skill control would be a better approach, or if it's even worth trying to improve this over just letting the sim core routine rewrite take care of this and keep the current behavior of default to all overlap for bosses and no overlap for mobs in the meantime.

**Comment by umang-p** [comment]
I had considered adding a skill control for her to let users specify exactly how many grenades they would like to see overlap, but defaulting to all overlap for bosses and none for mobs is more consistent with the behavior of other dolls with similar "either way kinda works" skills. So, I'll keep PR #21 as the fix for this for now. 

Thanks for the fix.
