### ISSUE TITLE
M82A1 3rd shot interaction with Bleeding Jane

### ISSUE THREAD

**Issue by AristocratMC** [umang-p/brainlets#40]
[Apparently it produces hilarious damage numbers](https://cdn.discordapp.com/attachments/621132699783921664/686732995654320168/image0.png)

[Example 2](https://cdn.discordapp.com/attachments/607755805894377488/686726501499928630/unknown.png)

(It shouldn't crit normally)

> BinaryHalibut Today at 10:52 PM
> sim bug, bleeding jane is coded in the sim as tacking a skill on to everyone that gets called and converts critrate into crit damage every time their critrate changes
> M82A1 doubles her skill damage every time she uses her skill the 2nd time
> The jill tacked on skill doesn't increment this counter but does count as a skill use when triggered
> Pink cano causes the jill skill to trigger a shit ton of times
> magic damage doubling commence
> taken to the logical extreme```

**Comment by umang-p** [comment]
Fixed in da0ecfd5098b6b1cf7837d273155b9e28b554978
